senials_frontend/src/App.js
senials_frontend/src/pages/hobby/hobby-board-post.module.css
senials_frontend/src/pages/mypage/mypageCalender.module.css
senials_frontend/src/pages/mypage/mypageMember.module.css
senials_frontend/src/pages/mypage/mypageModify.module.css
senials_frontend/src/pages/party/partyMeet.js
senials_frontend/src/pages/party/partyMeet.module.css
senials_frontend/src/pages/party/partyReview.js
senials_frontend/src/pages/party/partyReview.module.css
senials_frontend/src/pages/suggest-hobby/suggest-hobby-get.module.css

- #31 
App.js
hobby/hobby-board-post.module.css
mypage/mypageCalender.module.css
mypage/mypageMember.module.css
mypage/mypageModify.module.css
party/partyMeet.js
party/partyMeet.module.css
party/partyReview.js
party/partyReview.module.css
suggest-hobby/suggest-hobby-get.module.css
- body 태그 주석 처리
- 클래스 명으로 꾸민 css 제외 하고 공통 태그 사용한 부분 삭제
- 배경화면이 다 먹혔던 부분 없앴음
다른 페이지도 겹치는 css코드가 있다면 수정 필요

이걸 가장 먼저 머지해야함!! [design/frontend-31/common/common-modify]body 태그 주석 처리, 클래스 명으로 꾸민 css 제외 하고 공통 태그 사용한 부분 삭제

---

senials_frontend/src/App.js
senials_frontend/src/pages/mypage/mypage.js
senials_frontend/src/pages/mypage/mypageCalender.module.css
senials_frontend/src/pages/mypage/mypageLikedParty.js
senials_frontend/src/pages/mypage/mypageMade.js
senials_frontend/src/pages/mypage/mypageMember.js
senials_frontend/src/pages/mypage/mypageModify.js
senials_frontend/src/pages/mypage/mypageParticipate.js

- #42
- 마이페이지
- 남이 보는 사용자 페이지 완성
- 좋아요한 모임 페이지 레이아웃 구성
- 참여 모임 페이지 레이아웃 구성
- 생성 모임 페이지 레이아웃 구성
- 안에 내용물 채워넣기

[design/frontend-42/mypage] 마이페이지 완성, 각종 모임 목록 페이지 레이아웃 구성

---

senials_frontend/public/index.html
senials_frontend/src/index.js
senials_frontend/src/pages/common/common.module.css

- Resolve #62 
- index.js
- common.module.css
- index.html
- 공통 폰트 적용, Bootstrap 주석처리
- 글씨 크기 통일
- 버튼 크기 통일
-

[design/frontend-62/common/font] 공통 폰트 적용 및 글씨 크기, 버튼 크기 조정

---

senials_frontend/src/pages/common/common.module.css
senials_frontend/src/pages/mypage/mypage.js
senials_frontend/src/pages/mypage/mypageCalender.js
senials_frontend/src/pages/mypage/mypageCalender.module.css
senials_frontend/src/pages/mypage/mypageLike.js
senials_frontend/src/pages/mypage/mypageMember.js
senials_frontend/src/pages/mypage/mypageMember.module.css
senials_frontend/src/pages/mypage/mypageModify.js
senials_frontend/src/pages/mypage/mypageModify.module.css
senials_frontend/src/pages/party/partyMeet.js
senials_frontend/src/pages/party/partyMeet.module.css
senials_frontend/src/pages/party/partyMember.js
senials_frontend/src/pages/party/partyMember.module.css
senials_frontend/src/pages/party/partyReview.js
senials_frontend/src/pages/party/partyReview.module.css

- Resolve #32 
- 모임페이지, 마이페이지 버튼 크기 조정 및 오류 수정
- 버튼 hover 설정 필요

[design/frontend-32/mypageparty/modify-all] 모임페이지, 마이페이지 버튼 크기 조정 및 오류 수정

---

senials_frontend/src/App.js
senials_frontend/src/pages/mypage/MypageMember.js
senials_frontend/src/pages/mypage/MypageMember.module.css
senials_frontend/src/pages/party/PartyMeet.module.css
senials_frontend/src/pages/party/PartyMeetModify.js
senials_frontend/src/pages/party/PartyMember.module.css
senials_frontend/src/pages/party/PartyReview.module.css
senials_frontend/src/pages/party/PartyReviewModify.js

- Resolve #41 
- 중복 페이지 생성
- 모임 일정 수정 페이지 생성
- 모임 리뷰 수정 페이지 생성
-

[design/frontend-41/party/modifyPage] 모임 일정 수정, 모임 리뷰 수정 페이지 생성

---

senials_frontend/src/pages/hobby/HobbyDetailPost.js

- Resolve #65 
- css 파일 이름 변경으로 로딩 실패
- import 바
-

[design/frontend-59/hobby-board/hobby-board] 실행오류 css 변경 반영

---

senials_frontend/src/App.js
senials_frontend/src/layouts/Header.js
senials_frontend/src/pages/common/Common.module.css
senials_frontend/src/pages/mypage/MypageCalender.js
senials_frontend/src/pages/mypage/MypageCalender.module.css
senials_frontend/src/pages/mypage/MypageLike.js
senials_frontend/src/pages/mypage/MypageLikedParty.js
senials_frontend/src/pages/mypage/MypageMade.js
senials_frontend/src/pages/mypage/MypageMember.js
senials_frontend/src/pages/mypage/MypageMember.module.css
senials_frontend/src/pages/mypage/MypageModify.js
senials_frontend/src/pages/mypage/MypageModify.module.css
senials_frontend/src/pages/mypage/MypageParticipate.js
senials_frontend/src/pages/mypage/MypageParty.module.css
senials_frontend/src/pages/party/PartyMeet.js
senials_frontend/src/pages/party/PartyMeet.module.css
senials_frontend/src/pages/party/PartyMeetModify.js
senials_frontend/src/pages/party/PartyMember.js
senials_frontend/src/pages/party/PartyReview.js
senials_frontend/src/pages/party/PartyReview.module.css
senials_frontend/src/pages/party/PartyReviewModify.js

- Resolve #80 
- header.js
- 모임 페이지 양식
- 일정 참여 멤버 조회 페이지 연결
- 상세 일정 추가 페이지 연결
- 상세 일정 수정 페이지 연결
- 상세 모임 후기 작성 페이지 연결
- 상세 모임 후기 수정 페이지 연결
- 마이 페이지
- 회원정보 변경 페이지 연결
- 캘린더 페이지 연결
- 관심사 설정 페이지 연결
- 모임 전체 멤버 관리 페이지 연결
- 사용자 프로필 페이지 연결
- 좋아요 한 모임 보기 페이지 연결
- 참여 모임 보기 페이지 연결
- 생성 모임 보기 페이지 연결
- 세부 css 수정
- App.js
- MypageCalender.js (다른 페이지와 동일)
- userNumber 유지하면서 페이지 이동 필요

[feature/frontend-80/link-pages] 마이페이지, 모임 양식 페이지 연결 및 CSS 수정

---

senials_frontend/package-lock.json
senials_frontend/package.json
senials_frontend/src/index.js
senials_frontend/src/pages/admin/ManageUser.js
senials_frontend/src/redux/store.js

- #84 
- Redux Toolkit 디렉토리 구조 생성
- src/redux/store.js 
- index.js Provider 추가 및 store 연결
- axios 라이브러리 설치
-

[feature/frontend-84/redux/dir-structurer-composition]프론트앤드 Redux Toolkit 라이브러리 구조 구성

---

package-lock.json
senials_frontend/package-lock.json
senials_frontend/package.json
senials_frontend/public/img/NoImage.svg
senials_frontend/public/index.html
senials_frontend/src/pages/common/MainVer1.module.css
senials_frontend/src/pages/party/PartyBoardComponent/PopularPartyBoards.js
senials_frontend/src/pages/party/PartyBoardOverview.js
senials_frontend/src/redux/partySlice.js
senials_frontend/src/redux/store.js

- Resolve #88 
- 인기 추천 모임 출력
- 정렬 기능
- 최신순, 오래된순, 좋아요순, 조회순
- 검색 기능
- 모임 좋아요 기능
- 게시글 더보기 기능
- 결과 없을 때 문구 출력

[feature/frontend-88/partyboards-overview/list-request-api] 모임 목록 전체보기 REST API 호출

---

package-lock.json
senials_frontend/package-lock.json
senials_frontend/package.json
senials_frontend/public/img/NoImage.svg
senials_frontend/public/index.html
senials_frontend/src/App.js
senials_frontend/src/pages/common/MainVer1.module.css
senials_frontend/src/pages/party/PartyBoard.js
senials_frontend/src/pages/party/PartyBoardComponent/PopularPartyBoards.js
senials_frontend/src/pages/party/PartyBoardOverview.js
senials_frontend/src/redux/categorySlice.js
senials_frontend/src/redux/partySlice.js
senials_frontend/src/redux/store.js

- Resolve #93 
- 최근 오픈한 모임으로 대체

[feature/frontend-93/partyboards/list-request-api] 모임 목록 REST API 데이터 호출 및 출력

---

senials_frontend/src/pages/common/MainVer1.module.css
senials_frontend/src/pages/mypage/Mypage.js
senials_frontend/src/pages/mypage/MypageCalender.js
senials_frontend/src/pages/mypage/MypageCalender.module.css
senials_frontend/src/pages/mypage/MypageLike.js
senials_frontend/src/pages/mypage/MypageLike.module.css
senials_frontend/src/pages/mypage/MypageLikedParty.js
senials_frontend/src/pages/mypage/MypageMade.js
senials_frontend/src/pages/mypage/MypageModify.js
senials_frontend/src/pages/mypage/MypageModify.module.css
senials_frontend/src/pages/mypage/MypageParticipate.js
senials_frontend/src/pages/mypage/MypageParty.module.css

- Resolve #89
- 좋아요 한 모임 개수 출력
- 회원 탈퇴
- 링크 연결 중복현상 해결
- 관심사 설정 hobby 그룹화 후 출력
- 관심사 제목 출력 최대 5개만 허용
- 프로필 이미지 보여주기
- 프로필 이미지 수정 기능 추가하기

[feature/frontend-89/mypage/request-api] 좋아요 한 모임 개수 출력, 회원탈퇴, 링크 연결 수정

---

senials_frontend/package-lock.json
senials_frontend/package.json
senials_frontend/src/App.js
senials_frontend/src/pages/hobby/HobbyBoardPost.js
senials_frontend/src/redux/hobbySlice.js
senials_frontend/src/redux/store.js

- 87
- 취미 게시판 전체 보기 페이지 Rest api 호출
- hobbySlice.js 파일 추가 후 hobbyCard, hobbyTop3Card 카드 슬라이스 추가
- axios라이브러리 사용으로 rest api 값들을 받아오고, 출력될 수 있게끔 state 변경
-

[feature/frontend-87/hobbyboard/request-api] 취미 게시판 전체 보기 페이지 Rest api 호출

---

senials_frontend/src/pages/party/PartyDetail.js
senials_frontend/src/pages/party/PartyUpdate.js
senials_frontend/src/pages/party/PartyWrite.js

- Resolve #110 
- 이미지 업로드
- 모임 게시글 수정
수정됨 ㅇㅇ

[feature/frontend-110/partyboards/modify-request-api] 모임 수정 REST API 호출

---

senials_frontend/src/pages/party/PartyDetail.js
senials_frontend/src/pages/party/PartyUpdate.js
senials_frontend/src/pages/party/PartyWrite.js

- Resolve #123 
- 모임 삭제 REST API 호출

[feature/frontend-123/partyboards/delete-request-api] 모임 삭제 REST API 호출

---

senials_frontend/src/App.js
senials_frontend/src/pages/common/ScrollToTop.js
senials_frontend/src/pages/mainpage/MainPage.js
senials_frontend/src/pages/mypage/MypageMember.js
senials_frontend/src/pages/party/PartyBoard.js
senials_frontend/src/pages/party/PartyBoardComponent/PopularPartyBoards.js
senials_frontend/src/pages/party/PartyBoardOverview.js
senials_frontend/src/pages/party/PartyDetail.js
senials_frontend/src/redux/partyDetailSlice.js
senials_frontend/src/redux/store.js

- Resolve #130 
- 모임장 추방 기능
- 멤버 목록 더보기 기능
- ### 일반 유저일때
- ### 모임장일때

[feature/frontend-130/partymembers/request-api] 모임 멤버 목록 페이지 REST API 호출

---

senials_frontend/src/pages/party/PartyDetail.js
senials_frontend/src/pages/party/PartyMember.js

- Resolve #133
- 모임 일정 참여 인원 조회
- 일정 미참여 인원 조회 제한
-

[feature/frontend-133/meetmembers/request-api] 모임 일정 참여 멤버 목록 REST API 호출 및 데이터 출력

---

senials_frontend/src/pages/hobby/HobbyDetail.js
senials_frontend/src/pages/hobby/HobbyDetail.module.css
senials_frontend/src/pages/hobby/HobbyReview.js
senials_frontend/src/pages/hobby/HobbyReviewModify.js

- #137 
- 취미리뷰 이용비용 항목 누락 수정
- 취미 리뷰 기능 보강
- css 일부 수정
- 누락된 이용비용 조회 수정 출력
-

[bugfix/frontend-137/ Missing_database_value] 취미리뷰 이용비용 항목 누락 수정

---

senials_frontend/package.json
senials_frontend/src/layouts/Header.js
senials_frontend/src/layouts/Header.module.css
senials_frontend/src/pages/hobby/HobbyDetail.js
senials_frontend/src/pages/hobby/HobbyReview.js
senials_frontend/src/pages/hobby/HobbyReviewModify.js
senials_frontend/src/pages/login/Join.js
senials_frontend/src/pages/login/Login.js
senials_frontend/src/pages/mypage/MypageCalender.js
senials_frontend/src/pages/mypage/MypageLike.js
senials_frontend/src/pages/mypage/MypageLikedParty.js
senials_frontend/src/pages/mypage/MypageMade.js
senials_frontend/src/pages/mypage/MypageModify.js
senials_frontend/src/pages/mypage/MypageParticipate.js
senials_frontend/src/pages/party/PartyDetail.js

- Resolve #116 
- 토큰 설정
- 모임페이지

[feature/frontend-116/loginTest] 프론트&백 로그인테스트

---

senials_frontend/src/pages/party/PartyDetail.js

- Resolve #140
- 사라진 JSX 소괄호 문자 복구

[hotfix/frontend-140/partyboards/missing-character] 사라진 JSX 소괄호 문자 복구

---

senials_frontend/package.json
senials_frontend/src/App.js
senials_frontend/src/pages/party/PartyBoardOverview.js
senials_frontend/src/pages/party/PartyDetail.js

- Resolve #135 
- 변경된 라우터 Path에 맞게 각 컴포넌트 navigate 동작 수정
- ### App.js 각 컴포넌트 연결 및 동작 확인 완료

[feature/frontend-135/partyboards/modified-router-url] 모임 후기, 일정 작성 수정된 라우터 Path에 맞게 동작 수정

---

senials_frontend/package.json
senials_frontend/src/App.js
senials_frontend/src/pages/common/tokenApi.js
senials_frontend/src/pages/mypage/MypageMember.js
senials_frontend/src/pages/party/PartyBoard.js
senials_frontend/src/pages/party/PartyBoardOverview.js
senials_frontend/src/pages/party/PartyDetail.js
senials_frontend/src/pages/party/PartyMeet.js
senials_frontend/src/pages/party/PartyMember.js
senials_frontend/src/pages/party/PartyUpdate.js

- Resolve #143 
- 모임 관련 도메인 토큰과 함께 API 요청 처리 완료
- 토큰 api 요청 모듈화

[feature/frontend-143/partyboards/send-token] 모임 관련 도메인 토큰 포함 요청

---

senials_frontend/src/App.js
senials_frontend/src/pages/admin/ReportComponent.js

- #149 
- 신고 페이지 레이아웃 설계
- 신고 페이지 레이아웃 작성
- 라우트 연결
-

[feature/frontend-149/report/report] 신고 페이지 레이아웃 설계

---

senials_frontend/src/pages/admin/ManageReport.js
senials_frontend/src/pages/admin/ManageUser.js
senials_frontend/src/pages/admin/admin.module.css

- #86 
- 관리자 페이지 신고 관리 페이지 레이아웃 설계
- 관리자 페이지 신고 관리 페이지 레이아웃 구성
- 검색바 추가
- css 일부 변경
-

[design/frontend-86/admin/manage-report] 관리자 페이지 신고 관리 페이지 레이아웃 설계

---

senials_frontend/src/App.js
senials_frontend/src/pages/admin/AdminNav.js
senials_frontend/src/pages/admin/ManageCateogry.js
senials_frontend/src/pages/admin/ManageReport.js
senials_frontend/src/pages/admin/ManageSuggestion.js
senials_frontend/src/pages/admin/ManageUser.js
senials_frontend/src/pages/admin/admin.module.css
senials_frontend/src/pages/hobby/HobbyDetail.js

- #155 
- 관리자 카테고리 관리 페이지 레이아웃 설계
- 관리자 건의 관리 페이지 레이아웃 구성
- 라우트 연결
- css 일부 수정
- 네비게이션 바 컴포넌트화
- 날짜 추가
-

[feature/frontend-155/admin/manage_category] 관리자 카테고리 관리 페이지 레이아웃 설계

---

senials_frontend/src/index.js
senials_frontend/src/pages/admin/ReportComponent.js
senials_frontend/src/pages/common/MainVer1.module.css
senials_frontend/src/pages/hobby/HobbyDetail.js
senials_frontend/src/pages/party/PartyDetail.js
senials_frontend/src/pages/party/PartyMember.js

- Resolve #161
- index.js 불필요한 주석 제거함
- 신고 시 쿼리스트링 정보에 맞는 피신고 대상 기본 정보 출력
- report_type은 무슨 사유로 신고 했는지에 대한 분류
- report_target_type은 신고 대상이 어떤 객체인지에 대한 분류 (0 - USER, 1 - PARTY_BOARD, 2 - PARTY_REVIEW, 3 - HOBBY_REVIEW)
- 분류 좀 더 생각해봐야 할듯 그냥 추가만 하면 댐 <option> 태그들

[feature/frontend-161/reports/request-api] 신고 REST API 호출

---

senials_frontend/package.json
senials_frontend/src/App.js
senials_frontend/src/pages/admin/Suggestion.js
senials_frontend/src/pages/hobby/HobbyBoard.js

- #160 
- 건의 추가 페이지 건의 사항 추가 Rest api 호출, 구조 만들기
- 건의 추가 페이지 연결을 위한 취미 게시판 버튼 연결 수정
- post rest api를 활용한 건의 글 작성
-

[feature/frontend-160/suggestion/rest-api] 건의 추가 페이지 건의 사항 추가 Rest api 호출, 구조 만들기

---

senials_frontend/src/index.js
senials_frontend/src/pages/admin/ManageReport.js
senials_frontend/src/pages/admin/ReportComponent.js
senials_frontend/src/pages/admin/admin.module.css
senials_frontend/src/pages/common/MainVer1.module.css
senials_frontend/src/pages/hobby/HobbyDetail.js
senials_frontend/src/pages/party/PartyDetail.js
senials_frontend/src/pages/party/PartyMember.js
senials_frontend/src/pages/party/PartyReviewModify.js

- Resolve #163 
- 신고 내역 조회 및 링크 연결
- 관리자일 시 본인이 아니어도 수정 및 삭제가 가능토록 해야함

[feature/frontend-163/admin/report-management] 신고 관리 페이지 REST API 호출 및 출력 #163

---

senials_frontend/src/index.js
senials_frontend/src/pages/admin/ManageReport.js
senials_frontend/src/pages/admin/ManageUser.js
senials_frontend/src/pages/admin/ReportComponent.js
senials_frontend/src/pages/admin/admin.module.css
senials_frontend/src/pages/common/MainVer1.module.css
senials_frontend/src/pages/hobby/HobbyDetail.js
senials_frontend/src/pages/mainpage/MainPage.js
senials_frontend/src/pages/party/PartyBoard.js
senials_frontend/src/pages/party/PartyBoardComponent/PopularPartyBoards.js
senials_frontend/src/pages/party/PartyBoardOverview.js
senials_frontend/src/pages/party/PartyDetail.js
senials_frontend/src/pages/party/PartyMember.js
senials_frontend/src/pages/party/PartyReviewModify.js

- Resolve #167 
- 임시활동정지, 임시활동정지해제, 활동정지 기능 부여

[feature/frontend-167/admin/manage-user] 관리자 사용자 관리 REST API 호출

---

senials_frontend/package.json
senials_frontend/src/pages/admin/AdminNav.js
senials_frontend/src/pages/admin/ManageReport.js
senials_frontend/src/pages/admin/ManageUser.js
senials_frontend/src/pages/admin/admin.module.css

- Resolve #173 
- 불필요 요소 삭제
- 임시활동정지해제 버튼명 변경
- 버튼 정렬 변경

[design/frontend-173/admin/no-use-elements] 미사용 요소 삭제

---

senials_frontend/src/App.js
senials_frontend/src/pages/admin/ManageReport.js
senials_frontend/src/pages/admin/ManageUser.js
senials_frontend/src/pages/admin/ReportComponent.js

- Resolve #177 
- 성별 출력 수정
- Router 관리자 페이지 index 추가

[bugfix/frontend-177/unspecified-gender] 관리자 페이지 성별 출력 수정
